// Shared server-side data. Mirrors the region timing used in the client app.
const REGIONS = [
  { id:"wup", name:"Western U.P.", area:"Porkies, Keweenaw, Ontonagon", lat:46.80, lon:-89.73,
    green:[9,17], peakStart:[9,28], peakEnd:[10,6], bare:[10,16],
    drive:"Brockway Mountain Drive over the Keweenaw spine",
    hike:"Escarpment Trail to Lake of the Clouds, Porcupine Mountains",
    paddle:"Presque Isle River down to its Lake Superior mouth",
    note:"The first color in Michigan. Sugar maples blanket the Porkies." },
  { id:"eup", name:"Eastern U.P.", area:"Tahquamenon, Hiawatha, Whitefish", lat:46.58, lon:-85.22,
    green:[9,20], peakStart:[10,1], peakEnd:[10,9], bare:[10,18],
    drive:"M-123 through the Tahquamenon country",
    hike:"The river trail between Tahquamenon's upper and lower falls",
    paddle:"The Two Hearted, slow tea-dark water under hardwoods",
    note:"Birch and maple over the falls, often with the first lake-effect chill." },
  { id:"tip", name:"Tip of the Mitt", area:"Tunnel of Trees, Petoskey, Mackinaw", lat:45.50, lon:-84.99,
    green:[9,27], peakStart:[10,5], peakEnd:[10,13], bare:[10,22],
    drive:"Tunnel of Trees on M-119, Harbor Springs to Cross Village",
    hike:"The Lake Michigan shoreline at Wilderness State Park",
    paddle:"Crooked River and the Inland Waterway",
    note:"A canopy drive that closes overhead. Go on a weekday morning." },
  { id:"nwl", name:"Northwest Lower", area:"Sleeping Bear, Traverse City, Leelanau", lat:44.84, lon:-86.02,
    green:[9,30], peakStart:[10,8], peakEnd:[10,16], bare:[10,24],
    drive:"Pierce Stocking Scenic Drive, Sleeping Bear Dunes",
    hike:"Empire Bluff Trail to the overlook",
    paddle:"The Crystal River loop near Glen Arbor",
    note:"Color over dune and water, with vineyards turning on the peninsulas." },
  { id:"nel", name:"Northeast Lower", area:"Grayling, Au Sable, Rifle River, Oscoda", lat:44.66, lon:-84.71,
    green:[10,1], peakStart:[10,9], peakEnd:[10,17], bare:[10,25],
    drive:"River Road Scenic Byway to the Lumberman's Monument",
    hike:"Old-growth white pine at Hartwick Pines, Grayling",
    paddle:"The Au Sable Holy Waters, Burton's Landing to Wakeley",
    note:"Maple and aspen over dark pine, mirrored on slow current." },
  { id:"cen", name:"Central & Saginaw Bay", area:"Bay City, Midland, Mt Pleasant", lat:43.62, lon:-84.10,
    green:[10,7], peakStart:[10,14], peakEnd:[10,22], bare:[10,30],
    drive:"The river road through Chippewa Nature Center, Midland",
    hike:"The Tobico Marsh boardwalk at Bay City State Park",
    paddle:"The Tittabawassee through Midland",
    note:"Oak and maple on the bay flats, timed with the waterfowl push." },
  { id:"swl", name:"Southwest Lower", area:"Grand Rapids, Saugatuck, Kalamazoo", lat:43.00, lon:-86.10,
    green:[10,11], peakStart:[10,18], peakEnd:[10,26], bare:[11,3],
    drive:"Blue Star Highway along the Saugatuck dunes",
    hike:"The dune trails at P.J. Hoffmaster State Park",
    paddle:"The lower Kalamazoo River",
    note:"Lakeshore microclimates hold color a little later here." },
  { id:"sel", name:"Southeast Lower", area:"Detroit, Ann Arbor, Irish Hills", lat:42.28, lon:-83.74,
    green:[10,13], peakStart:[10,20], peakEnd:[10,28], bare:[11,5],
    drive:"The Irish Hills along US-12",
    hike:"The Waterloo-Pinckney Trail through Waterloo Rec Area",
    paddle:"The Huron River through Ann Arbor",
    note:"The last peak in the state. Oaks hold russet well into November." },
];

const CANOE = [
  { name:"Au Sable River", region:"nel", stretch:"Holy Waters: Burton's Landing to Wakeley Bridge", level:"Easy, steady current", hours:"3 to 4 hr", liveries:"Gates Au Sable Lodge, Carlisle, Penrod's, Borchers in Grayling" },
  { name:"Rifle River", region:"nel", stretch:"Rifle River Rec Area down toward Sterling", level:"Easy, family", hours:"2 to 5 hr", liveries:"Liveries around Rose City and Sterling" },
  { name:"Pine River", region:"nwl", stretch:"Near Wellston, Manistee National Forest", level:"Intermediate, fast", hours:"2 to 4 hr", liveries:"Horina Canoe Rental, Pine River Paddlesport Center" },
  { name:"Platte River", region:"nwl", stretch:"Honor down to Lake Michigan", level:"Easy", hours:"2 to 3 hr", liveries:"Riverside Canoe Trips" },
  { name:"Crystal River", region:"nwl", stretch:"Glen Arbor loop, edge of Sleeping Bear", level:"Easy", hours:"about 2 hr", liveries:"Crystal River Outfitters" },
  { name:"Jordan River", region:"nwl", stretch:"Jordan Valley near East Jordan", level:"Advanced, narrow and fast", hours:"2 to 3 hr", liveries:"Jordan Valley Outfitters, Swiss Hideaway" },
  { name:"Manistee River", region:"nwl", stretch:"Mesick area, pairs with the Manistee River Trail", level:"Intermediate", hours:"half to full day", liveries:"Wilderness Canoe Trips, Chippewa Landing" },
  { name:"Two Hearted River", region:"eup", stretch:"Remote eastern U.P. to Lake Superior", level:"Intermediate, remote", hours:"half day", liveries:"Rainbow Lodge near the mouth" },
  { name:"Sturgeon River", region:"tip", stretch:"Near Indian River, edge of Pigeon River Country", level:"Intermediate, fast", hours:"2 to 3 hr", liveries:"Big Bear Adventures" },
  { name:"Huron River", region:"sel", stretch:"Ann Arbor, Argo to Gallup", level:"Easy, urban", hours:"about 2 hr", liveries:"Argo and Gallup Livery, Ann Arbor" },
];

module.exports = { REGIONS, CANOE };
