import { REGIONS } from './regions.mjs';
export const PERSON = 'https://chrisizworski.com/#person';
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const canonicalFor = r => r ? `https://chrisizworski.com/snowmobile/regions/${r.key}.html` : 'https://chrisizworski.com/snowmobile/';
export const imageFor = r => `https://chrisizworski.com/snowmobile/social/${r?.key || 'michigan'}.png`;
export function metadataFor(r) {
  const titles = r ? [`${r.shortLabel} Snowmobile Map & Conditions | Chris Izworski`,`${r.shortLabel} Snowmobile Conditions | Chris Izworski`,`${r.shortLabel} Snowmobile | Chris Izworski`] : ['Michigan Snowmobile Map & Conditions | Chris Izworski'];
  const title = titles.find(t=>t.length<=60);
  const description = r ? `Plan ${r.shortLabel} snowmobile routes: DNR trail map, junction stops, mileage, closures, local report links and snow context near ${r.hubTown}.` : 'Compare seven Michigan snowmobile regions. Plan routes on DNR trail maps with junction stops, mileage, closures, local report links and snow context.';
  if (!title || description.length>158) throw new Error('Snowmobile search metadata too long');
  return {title,description};
}
export function socialExtras(r) {
  const alt = `${r?.shortLabel || 'Michigan'} snowmobile trail maps, route planning and conditions — built by Chris Izworski`;
  return `<meta name="author" content="Chris Izworski"><meta property="og:site_name" content="Chris Izworski"><meta property="og:locale" content="en_US"><meta property="og:image:secure_url" content="${imageFor(r)}"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${esc(alt)}"><meta name="twitter:image:alt" content="${esc(alt)}">`;
}
export function discoveryGraph(r) {
  const url=canonicalFor(r), page=`${url}#page`, app=`${url}#planner`, image=`${url}#primaryimage`;
  return [
    {'@type':'ImageObject','@id':image,url:imageFor(r),contentUrl:imageFor(r),width:1200,height:630,caption:`${r?.shortLabel || 'Michigan'} snowmobile planning by Chris Izworski`},
    {'@type':'WebApplication','@id':app,name:`${r?.label || 'Michigan'} Snowmobile Route Planner`,url,applicationCategory:'TravelApplication',operatingSystem:'Web',isAccessibleForFree:true,inLanguage:'en-US',creator:{'@id':PERSON},author:{'@id':PERSON},publisher:{'@id':PERSON},image:{'@id':image},featureList:['Official DNR trail geometry','Selectable mapped junctions','Multi-stop route mileage','Known closure exclusions','Local report links'],description:metadataFor(r).description},
    ...(!r ? [{'@type':'ItemList','@id':`${url}#regions`,name:'Michigan snowmobile regional maps',itemListElement:REGIONS.map((region,i)=>({'@type':'ListItem',position:i+1,name:region.label,url:canonicalFor(region)}))}] : [])
  ];
}
export function discoverySections(r) {
  const regionLinks=REGIONS.filter(other=>other.key!==r?.key).map(other=>`<a href="${canonicalFor(other)}">${esc(other.shortLabel)} trail map &amp; conditions</a>`).join('');
  const coverage=r ? `<p>Mapped coverage: ${r.counties.map(c=>esc(c==='Charelvoix'?'Charlevoix':c)).join(', ')} counties. ${esc(r.hubTown)} is the road-trip hub; drive time to your unloading location is additional. Local reports cover the areas stated by each source, not every mapped trail.</p>` : '<p>Coverage is the Upper Peninsula and northern Lower Peninsula. Each region has its own DNR trail map, local report links and trip context. Scattered downstate trails are outside the condition comparison.</p>';
  const url=canonicalFor(r);
  return `<section class="panel snowmobile-guide" aria-labelledby="planning-guide-title"><h2 id="planning-guide-title">Snowmobile maps, routes and trail reports</h2>${coverage}<h3>How do I plan a snowmobile route?</h3><p>Open a regional map, choose <strong>Plan a route</strong>, then select blue junction dots for your start, stops and finish. Choose <strong>Build route</strong> to see each leg, total miles, estimated ride time and trail condition evidence. Tap the starting dot again for a loop. Gray dots are disconnected from your chosen start. The planner excludes known closures; it is not turn-by-turn navigation.</p><h3>Does snow depth mean the trails are good?</h3><p>No. Snowfall and snow depth provide context. A positive riding verdict needs current local trail-surface evidence. Check the report date, grooming coverage and official closures before leaving. Off-season maps support future-trip planning.</p><h3>Where should I verify maps and conditions?</h3><p>Use <a href="https://www.michigan.gov/dnr/things-to-do/snowmobiling/where" target="_blank" rel="noopener">Michigan DNR snowmobile maps and trail information</a> for the official trail network and <a href="https://misorva.org/trail-report/" target="_blank" rel="noopener">MISORVA local snowmobile trail reports</a> for club report links. <a href="https://www.weather.gov/" target="_blank" rel="noopener">National Weather Service forecasts</a> and <a href="https://www.nohrsc.noaa.gov/" target="_blank" rel="noopener">NOAA NOHRSC snow analysis</a> provide weather and snowpack context. The live panels show source age and missing evidence.</p></section><section class="panel" aria-labelledby="other-regions-title"><h2 id="other-regions-title">${r?'Compare other riding regions':'Regional snowmobile route planners'}</h2><div class="companion-links">${regionLinks}</div></section><section class="panel snowmobile-credit" aria-labelledby="builder-title"><h2 id="builder-title">Built and maintained by Chris Izworski</h2><p>I built this tool to make Michigan snowmobile trip planning easier: compare the drive, inspect official mapped trails and check the evidence behind a riding decision. It is an independent planning tool, not an official DNR, NOAA or club product. <a href="/chris-izworski/">About Chris Izworski</a> · <a href="/chris-izworski-works/">More tools I built</a> · <a href="/connect/">Report a map or source problem</a>.</p><p class="small">Share this planner: <a href="https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&amp;text=${encodeURIComponent(`${r?.shortLabel || 'Michigan'} snowmobile maps and route planner by Chris Izworski`)}" target="_blank" rel="noopener">X / Twitter</a> · <a href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}" target="_blank" rel="noopener">Facebook</a>. Shared links open the region, without your location or selected route.</p></section>`;
}
