// Source links checked October 5, 2026. These are manual verification handoffs,
// not region-wide surface observations and never inputs to the condition score.
export const PLANNING={
  'eastern-up':{note:'Sault Ste. Marie is the road-time reference. A ride around the Soo is a different staging choice from Paradise, Newberry or Munising; check the club responsible for your exact route.',reports:[{name:'Sault Snowmobile Association',url:'https://misorva.org/trail-reports/sault-snowmobile-association/',scope:'Sault-area club report; does not cover the entire Eastern U.P.'}]},
  'keweenaw-copper-country':{note:'Houghton is the road-time reference. Choose your staging point before using a hub drive time to budget the day; riding farther up the peninsula requires additional travel.',reports:[{name:'Visit Keweenaw snow and trail reports',url:'https://www.visitkeweenaw.com/outdoors/winter-activities/snowfall-trail-conditions/',scope:'Check the snowmobile section and its report date; ski reports and snowfall totals are separate evidence.'}]},
  'central-western-up':{note:'Marquette is the road-time reference, not a travel estimate for Ironwood or every western U.P. trail. Pick a local staging area and verify that trail system separately.',reports:[{name:'Moose Country Snowmobile Club',url:'https://misorva.org/trail-reports/moose-country-snowmobile-club/',scope:'Local club coverage only; use the MISORVA directory for other central and western U.P. systems.'}]},
  'grayling-gaylord':{note:'Road time ends at Grayling. The corridor continues through Frederic and Waters toward Gaylord; a good report at one end cannot establish the condition of the whole ride.',reports:[{name:'Greater Grayling Snowmobile Association',url:'https://misorva.org/trail-reports/greater-grayling-snowmobile-assoc/',scope:'Grayling-area report.'},{name:'Gaylord Area Snowmobile Trails Council',url:'https://misorva.org/trail-reports/gaylord-area-snowmobile-trials-council/',scope:'Gaylord-area report; verify both ends of a corridor trip.'}]},
  'northeast-sunrise':{note:'Cheboygan is the road-time reference. Atlanta, Mio and Oscoda require separate staging and local-condition checks rather than borrowing Cheboygan conditions.',reports:[{name:'Cheboygan Trail Blazers',url:'https://misorva.org/trail-reports/cheboygan-trail-blazers/',scope:'Cheboygan-area club report; not the whole Sunrise Side.'}]},
  'northwest-michigan':{note:'Petoskey is the road-time reference. For a ride from Kalkaska or Traverse City, verify the local club and staging area instead of treating Petoskey as your trailhead.',reports:[{name:'Petoskey Snowmobile Club',url:'https://misorva.org/trail-reports/petoskey-snowmobile-club/',scope:'Petoskey-area club report; read the timestamp and confirm any closure locally.'}]},
  'west-michigan':{note:'Cadillac is the road-time reference. Manistee and Baldwin are separate starting areas; verify staging access and the relevant groomer report for your chosen trail.',reports:[{name:'Cadillac Winter Promotions',url:'https://misorva.org/trail-reports/cadillac-winter-promotions/',scope:'Cadillac-area club report; not a report for every trail in this region.'}]}
};
export function planningFor(key){return PLANNING[key]||{note:'Road times end at a region hub; staging and trailhead travel are additional.',reports:[]};}
